sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_23c8c67f0fc7_key -iv $encrypted_23c8c67f0fc7_iv -in multi-k8s-291422-23e04d143229.json.enc -out multi-k8s-291422-23e04d143229.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-acccount.json
